#!/usr/bin/env bash
#
# Release absence audit (019 FR-025, FR-026, FR-028, SC-004) — prove that no seeding path is
# present in the built Release binary.
#
# `scripts/import-path-audit.sh`'s tenth scan is the source-level half: every file under
# `ios/Sources/DebugSeed/` opens with `#if DEBUG`. This is the half that reaches the artifact,
# because a guard that is present but *ineffective* — a file compiled into a target whose
# Release configuration lacks the DEBUG condition, a `Project.swift` glob that puts the
# directory somewhere unexpected — passes a source scan and ships anyway. Only the binary knows.
#
# 🚨 THE TRAP THIS SCRIPT EXISTS TO AVOID. `-showBuildSettings` reports STRIP_STYLE = all and
# STRIP_SWIFT_SYMBOLS = YES, but DEPLOYMENT_POSTPROCESSING = NO — stripping runs on `install`
# and `archive`, not on `build`. Measured on this repository (research E4, re-measured by 019
# T003 on the working machine): the Release *build* product carries **4,511** symbols (12,249
# counting the debug map); the same binary after `strip -rSTx` carries **156**, and
# `FilterChromeLayout` has left `nm` entirely.
# A symbol scan over a stripped artifact is **vacuously green** — it finds nothing because there
# is nothing to find, and reports success.
#
# Three consequences, all load-bearing:
#   1. This script BUILDS ITS OWN ARTIFACT. It never scans a binary somebody else produced,
#      because it cannot know how that one was made.
#   2. It SELF-CHECKS before it concludes: it first finds two things it knows must be present —
#      a shipping symbol and a shipping string literal — and fails as FAIL (inconclusive) if
#      either is missing. That is the whole difference between a proof and a formality.
#   3. It scans BOTH `nm` and `strings`. They fail differently: stripping removed the symbol
#      while the string literal survived, and a code path can carry an identifying literal with
#      no distinguishable symbol at all.
#
# It is deliberately NOT part of `make import-audit`: that gate is a sub-second grep that people
# run constantly, and a 16-second build inside it is the reason somebody stops running it
# (FR-028, SC-014). Run it with `make release-audit`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE="$REPO_ROOT/ios/Kaname.xcworkspace"

# The workspace is generated by Tuist and is not in the repository. Say so by name: an
# `xcodebuild` stack trace about a missing workspace sends the reader looking at Xcode.
if [ ! -d "$WORKSPACE" ]; then
    echo "release-audit: FAIL — $WORKSPACE does not exist. Run \`make ios-gen\` first." >&2
    exit 1
fi

DD="$(mktemp -d)"
trap 'rm -rf "$DD"' EXIT

echo "release-audit: building a Release binary (this is the ~16s the gate costs)…"

xcodebuild -workspace "$WORKSPACE" -scheme Kaname \
    -configuration Release -sdk iphonesimulator \
    -derivedDataPath "$DD" CODE_SIGNING_ALLOWED=NO build > "$DD/build.log" 2>&1 || {
    echo "release-audit: FAIL — the Release build failed, so nothing has been proved:" >&2
    # The compiler is a gate in its own right here: an unguarded shipping reference to a
    # DEBUG-only type does not quietly ship, it fails to compile in Release (019 T013). That
    # makes the error lines the most useful thing this block can print — a blind `tail` of an
    # xcodebuild log is forty lines of module-cache chatter and no diagnosis.
    grep -E '(error|fatal error):' "$DD/build.log" | head -20 >&2 || tail -40 "$DD/build.log" >&2
    exit 1
}

BIN="$DD/Build/Products/Release-iphonesimulator/Kaname.app/Kaname"

if [ ! -f "$BIN" ]; then
    echo "release-audit: FAIL (inconclusive) — the build succeeded but produced no binary at" >&2
    echo "$BIN — the product path has moved and this scan was about to pass over nothing." >&2
    exit 1
fi

# --- Self-check 0: the seeding sources must actually be IN the project ----------------------
# ⚠️ Tuist resolves `sources: ["Sources/**"]` at **generation** time, so a file added since the
# last `make ios-gen` is not in `project.pbxproj` and is not compiled by anything. An absence
# scan over that build is vacuous in exactly the way the strip trap is: the seeding path is
# missing from the artifact because it was never built, not because the guard held. This cost
# three green runs during 019 T011–T013 before it was noticed, and every one of them looked
# like a pass. So membership is asserted before absence is concluded.
PBXPROJ="$REPO_ROOT/ios/Kaname.xcodeproj/project.pbxproj"
SEED_DIR="$REPO_ROOT/ios/Sources/DebugSeed"

if [ -d "$SEED_DIR" ]; then
    while IFS= read -r seed_file; do
        base="$(basename "$seed_file")"
        if [ -z "$(grep -F "$base" "$PBXPROJ" || true)" ]; then
            echo "release-audit: FAIL (inconclusive) — $base is not in the generated project," >&2
            echo "so nothing compiled it and its absence from the binary proves nothing." >&2
            echo "Run \`make ios-gen\` and try again (Tuist resolves its source globs at" >&2
            echo "generation time, not at build time)." >&2
            exit 1
        fi
    done < <(find "$SEED_DIR" -name '*.swift')
fi

# Both tools are run ONCE and their output held, for two reasons. The cheap one: four passes
# over a 2.6 MB binary is three more than the scan needs. The load-bearing one: under
# `set -euo pipefail`, `nm "$BIN" | grep -q …` fails **even when it matches** — `grep -q`
# exits the instant it finds the anchor, `nm` dies of SIGPIPE (141), and `pipefail` reports the
# pipeline as failed. That is how this script's first honest run declared itself inconclusive
# against a binary that carried both anchors (019 T010). It is the same hazard the nine sibling
# scans end `|| true` for, wearing a different hat: there, a `grep` that finds nothing exits 1;
# here, a `grep` that finds something kills its producer. Match in a variable, never in a pipe.
#
# ⚠️ `nm`, NOT `nm -a`. `-a` includes the debug map — the stab entries naming every source file
# the target compiled — so a correctly guarded `ios/Sources/DebugSeed/DebugSeed.swift` shows up
# three times (`SO …/DebugSeed/`, `OSO …/DebugSeed.o`, `SO DebugSeed.swift`) in a binary that
# contains none of its code (measured, 019 T012). That is a false positive on a *clean* tree,
# and a gate that fails when nothing is wrong is a gate somebody deletes. Plain `nm` reports the
# symbols the binary actually defines and references — 4,511 of them here, against 12,249 stab
# entries — and still catches the real break: an unguarded, referenced `DebugSeed` emits
# `_$s6Kaname9DebugSeedOMa` and friends (019 T013). What the debug map would have told us —
# "was this file even compiled?" — self-check 0 above answers directly, and truthfully.
symbols="$(nm "$BIN")"
literals="$(strings -a "$BIN")"

# --- Self-check: the scan must first be shown capable of finding something ------------------
# Two anchors, one per scanning technique, both from shipped 018 code. If either is missing the
# artifact is stripped, mis-built or in the wrong place, and an absence measured over it means
# nothing. Verdict is FAIL (inconclusive), which is a different sentence from "seeding found".
SYMBOL_ANCHOR='FilterChromeLayout'
LITERAL_ANCHOR='Show all accounts'

if [ -z "$(printf '%s\n' "$symbols" | grep -F "$SYMBOL_ANCHOR" || true)" ]; then
    echo "release-audit: FAIL (inconclusive) — the binary carries no '$SYMBOL_ANCHOR' symbol." >&2
    echo "It is stripped or mis-built (a stripped Kaname has 156 symbols, not ~4,500), so an" >&2
    echo "absence scan over it would be vacuously green. Nothing has been proved either way." >&2
    exit 1
fi

if [ -z "$(printf '%s\n' "$literals" | grep -F "$LITERAL_ANCHOR" || true)" ]; then
    echo "release-audit: FAIL (inconclusive) — no known shipping literal ('$LITERAL_ANCHOR')" >&2
    echo "in the binary's strings. The scan cannot show it is able to find anything, so its" >&2
    echo "silence about seeding means nothing." >&2
    exit 1
fi

# --- The absence itself ---------------------------------------------------------------------
DENYLIST=(DebugSeed SeedScenario SeedStatement SeedRow KANAME_SEED_SCENARIO applyIfRequested)
pattern="$(printf '%s|' "${DENYLIST[@]}")"
pattern="(${pattern%|})"

sym_hits="$(printf '%s\n' "$symbols" | grep -E "$pattern" || true)"
str_hits="$(printf '%s\n' "$literals" | grep -E "$pattern" || true)"

if [ -n "$sym_hits" ] || [ -n "$str_hits" ]; then
    echo "release-audit: FAIL — a seeding path is present in the Release binary:" >&2
    [ -n "$sym_hits" ] && { echo "  symbols (nm):" >&2; echo "$sym_hits" >&2; }
    [ -n "$str_hits" ] && { echo "  literals (strings):" >&2; echo "$str_hits" >&2; }
    echo "Seeding fabricates a person's financial history and must not exist in a build" >&2
    echo "anybody installs (019 FR-025, SC-004). Check the #if DEBUG guards and which target" >&2
    echo "compiles ios/Sources/DebugSeed/." >&2
    exit 1
fi

symbol_count="$(printf '%s\n' "$symbols" | wc -l | tr -d ' ')"
term_count="${#DENYLIST[@]}"
echo "release-audit: OK (Release binary carries no seeding path; $symbol_count symbols scanned, $term_count terms)"
